#!/bin/bash
mkdir lst &> /dev/null
mkdir map &> /dev/null

for i in $( ls *.asm); do
    src=${i%.*}
    avra -I /usr/share/avra $src.asm -o hex/$src.hex -l lst/$src.lst -m map/$src.map &> /dev/null
    if [ $? -eq 0 ]; then
        echo OK : $src
    else
        echo ERR: $src
    fi

done

rm *cof
rm *obj
rm *eep.hex
